# Change these first
owner: spielers # Your GitHub username
repo: hostics # Your GitHub repository name

# Add your sites here
sites:
  - name: Gamitics
    url: https://gamitics.com/
  - name: surajpatil.tech
    url: http://surajpatil.tech/
  - name: businessengineer.in
    url: http://businessengineer.in
  - name: impulse-e-education.site
    url: https://impulse-e-education.site
  - name: kccbls.tech
    url: https://kccbls.tech
  - name: impulse-e-education.site
    url: https://impulse-e-education.site
  - name: guruashramfaculty.in
    url: https://guruashramfaculty.in
  - name: graphicxpress.in 
    url: http://graphicxpress.in/
  - name: Aimetix.com
    url: https://aimetix.com
  - name: Acmeera.com
    url: https://acmeera.com
  - name: longhorns.in
    url: https://longhorns.in
  - name: Aimetix.com
    url: https://aimetix.com
  - name: harekrishnaredevelopers.site
    url: https://harekrishnaredevelopers.site
  - name: sonecacolabeach.com
    url: https://sonecacolabeach.com
  - name: Test for HEAD
    method: HEAD
    url: https://www.google.com
  - name: Secret Site
    url: $SECRET_SITE
  - name: TCP ping
    url: 1.1.1.1

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: hostics.eu.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
